server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT}
      authentication-database: admin
      database: mz2mo

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}