server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/mz2mo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

mz2mo:
  music:
    vote:
      max-vote-count: ${MUSIC_VOTE_MAX_VOTE_COUNT:3}
cors:
  allowedOrigins: ${ALLOWED_ORIGINS_LIST:http://localhost:3000}
